language: java

jdk:
  - oraclejdk8

branches:
  only:
    - develop

addons:
  apt:
    packages:
      - libssl-dev
      - libffi-dev
      - build-essential
      
dist: trusty

dist: trusty

install:
  - nvm install lts/*

script:
  - 'git clone $SDK_REPO'
  - './mvnw -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean install -f azure-spring-cloud-sdk/resource-manager/v2019_05_01_preview/pom.xml'
  - './mvnw -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify'
  - './mvnw -B -pl azure-webapp-maven-plugin,azure-maven-plugin-lib cobertura:cobertura'

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)
