language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - develop

addons:
  apt:
    packages:
      - libssl-dev
      - libffi-dev
      - python-dev
      - build-essential

install:
  - pip install azure-cli --user
  - nvm install lts/*
  - npm i -g azure-functions-core-tools@core --unsafe-perm true

script:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ];
    then ./mvnw verify -P it;
    else ./mvnw verify;
    fi
  - './mvnw cobertura:cobertura'

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)
