language: java

jdk:
  - oraclejdk7

branches:
  only:
    - master

before_install:
  - sudo apt-get update && sudo apt-get install -y libssl-dev libffi-dev python-dev build-essential
  - sudo pip install azure-cli

script: "mvn cobertura:cobertura"

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)
