branches:
  only:
    - master
    - develop

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  PYTHON: "C:\\Python35"
  CLIENT_ID:
    secure: rSMXqU3uFoLjHUvut92UhV/DxNcC5csNr/BSw0N2UryRVhSge2tVYvz5PAHXSJla
  TENANT_ID:
    secure: s5TV0C1mfbi57ez2M9rVXGWHjY3AsoK6nASX8oUWeUg9Z8HW6dXxa3bhc+Oc9SRF
  KEY:
    secure: 0/sG+24ZzSK1djeM0EFg+8RmbzOkssudRWGnjDoGplwd/97i6Eu0Tf48zbiqgoZG

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%JAVA_HOME%\bin;%PATH%
  - cmd: python -m pip install azure-cli
  - cmd: copy "C:\Program Files (x86)\Apache\Maven\bin\mvn.cmd" "C:\Program Files (x86)\Apache\Maven\bin\mvn.bat"

build_script:
  # - mvnw.cmd clean install -B -V
  - ps: >-
      If ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
        ./mvnw.cmd verify 
      } Else {
        ./mvnw.cmd verify -P it 
      }
