branches:
  only:
    - master
    - develop

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  PYTHON: "C:\\Python35"
  dotnetcore_version: 2.1.302
  nodejs_version: "8"

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%JAVA_HOME%\bin;%PATH%
  - cmd: npm i -g azure-functions-core-tools@core --unsafe-perm true
  - cmd: python -m pip install azure-cli
  - cmd: copy "C:\Program Files (x86)\Apache\Maven\bin\mvn.cmd" "C:\Program Files (x86)\Apache\Maven\bin\mvn.bat"

build_script:
  - cmd: git clone %SDK_REPO% && mvnw clean install -B -f azure-spring-cloud-sdk/resource-manager/v2019_05_01_preview/pom.xml && mvn clean install && mvn -B -f azure-functions-maven-plugin/pom.xml clean verify -P it

on_failure:
  - ps: |
      .\ci\ps\errorNotificationSender.ps1 "azure-functions-maven-plugin"

