branches:
  only:
    - master
    - develop

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  PYTHON: "C:\\Python35"

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%JAVA_HOME%\bin;%PATH%
  - cmd: python -m pip install azure-cli
  - cmd: copy "C:\Program Files (x86)\Apache\Maven\bin\mvn.cmd" "C:\Program Files (x86)\Apache\Maven\bin\mvn.bat"

build_script:
  - cmd: mvn clean install && mvn -f azure-webapp-maven-plugin/pom.xml clean verify -P it

on_failure:
  - ps: |
      .\ci\ps\errorNotificationSender.ps1 "azure-webapp-maven-plugin"
