branches:
  only:
    - develop
    
environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  dotnetcore_version: 2.1.302
  nodejs_version: "8"

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%JAVA_HOME%\bin;%PATH%
  - cmd: copy "C:\Program Files (x86)\Apache\Maven\bin\mvn.cmd" "C:\Program Files (x86)\Apache\Maven\bin\mvn.bat"

build_script:
  - ps: |
      $proc =  .\ci\ps\e2etest.ps1
      
test_script:
  - ps: |
      $response = curl http://localhost:7071/api/HttpExample?name=CI
      $success = $response.Content -eq "Hello, CI"
      if (-not $success) { exit 1 } 

on_finish:
  - ps: | 
      Stop-Process -Id $proc.Id -Erroraction Ignore
      # Output standard input stream and error stream
      Write-Output "Standard input stream :" (gc ".\output.txt")
      Write-Output "Standard error stream :" (gc ".\error.txt")
