branches:
  only:
    - feature-spring

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

install:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%

build_script:
  - ps: |
      git clone $Env:SDK_REPO
      ./mvnw clean install -f azure-spring-cloud-sdk/resource-manager/v2019_05_01_preview/pom.xml
      ./mvnw clean verify
